apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  annotations:
    mia-platform.eu/version: 14.1.0
  labels:
    app.kubernetes.io/part-of: frengo-test-github-13
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: PROD
    mia-platform.eu/tenant: 6b38a8ec-816c-487c-986d-c59edb294ea6
