apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../configuration
  - api-gateway-envoy-config.configmap.yml
  - swagger-aggregator-config.configmap.yml
  - api-gateway.deployment.yml
  - api-gateway.service.yml
  - swagger-aggregator.deployment.yml
  - swagger-aggregator.service.yml
  - api-gateway.serviceaccount.yml
  - swagger-aggregator.serviceaccount.yml
