apiVersion: v1
kind: Service
metadata:
  name: swagger-aggregator
  annotations:
    mia-platform.eu/version: 14.1.0
  labels:
    app: swagger-aggregator
    app.kubernetes.io/name: swagger-aggregator
    app.kubernetes.io/version: 3.9.4
    app.kubernetes.io/component: custom
    app.kubernetes.io/part-of: frengo-test-github-13
    app.kubernetes.io/managed-by: mia-platform
    mia-platform.eu/stage: DEV
    mia-platform.eu/tenant: 6b38a8ec-816c-487c-986d-c59edb294ea6
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: null
  selector:
    app: swagger-aggregator
